/**
 * Structured Logger for StrategicAudit Pro
 *
 * Replaces console.log/warn/error with structured JSON logging.
 * Compatible with Vercel Logs, Datadog, and other log aggregators.
 *
 * Supports request ID correlation via AsyncLocalStorage.
 *
 * Usage:
 *   import { logger } from "@/lib/logger";
 *   logger.info("Project created", { projectId, userId });
 *   logger.error("Failed to save", { error, context: "audit-save" });
 */

type LogLevel = "debug" | "info" | "warn" | "error";

interface LogContext {
  [key: string]: unknown;
}

/**
 * Request-scoped correlation data merged into every log line emitted while
 * the store is active (G1 — Correlation IDs).
 *
 * - `requestId`: `x-request-id` generated by `src/proxy.ts`.
 * - `userId`: populated by wrappers that already resolved the principal
 *   (`withRateLimit` con `authenticate`).
 * - `correlationId`: identifier that survives async hand-offs (Trigger.dev
 *   payloads, cron chains, SIEM exports).
 */
export interface RequestContext {
  requestId?: string;
  userId?: string;
  correlationId?: string;
}

interface RequestContextStore {
  getStore: () => RequestContext | undefined;
  run: <T>(store: RequestContext, fn: () => T) => T;
}

/** AsyncLocalStorage for request-scoped context (requestId, userId, etc.). */
let requestContext: RequestContextStore | null = null;

if (typeof window === "undefined") {
  // Server-side only
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { AsyncLocalStorage } = require("node:async_hooks") as { AsyncLocalStorage: new <T>() => { getStore: () => T | undefined; run: <R>(store: T, fn: () => R) => R } };
    requestContext = new AsyncLocalStorage<RequestContext>();
  } catch {
    // AsyncLocalStorage not available
  }
}

/**
 * Runs `fn` with `context` as the active request scope. Every `logger.*`
 * call made inside `fn` (including awaited async work) merges the context.
 *
 * Fail-safe: if `AsyncLocalStorage` is unavailable (edge runtime / browser)
 * the function is invoked untouched, so callers never break.
 *
 * @example
 *   runWithRequestContext({ requestId }, () => updateSession(request));
 */
export function runWithRequestContext<T>(context: RequestContext, fn: () => T): T {
  return requestContext ? requestContext.run(context, fn) : fn();
}

/** Returns the active request scope, or `undefined` outside of one. */
export function getRequestContext(): RequestContext | undefined {
  return requestContext?.getStore();
}

/** Convenience accessor for the active `x-request-id`. */
export function getRequestId(): string | undefined {
  return requestContext?.getStore()?.requestId;
}

/**
 * Identifier used to correlate work that leaves the current request
 * (Trigger.dev payloads, cron chains, SIEM exports). Falls back to
 * `requestId` when no explicit correlation id was set.
 */
export function getCorrelationId(): string | undefined {
  const store = requestContext?.getStore();
  return store?.correlationId ?? store?.requestId;
}

function formatTimestamp(): string {
  return new Date().toISOString();
}

function log(level: LogLevel, message: string, context?: LogContext | unknown): void {
  // Normalize unknown context to LogContext
  const normalizedContext: LogContext | undefined =
    context && typeof context === "object" && !Array.isArray(context)
      ? context as LogContext
      : context !== undefined && context !== null
        ? { value: context }
        : undefined;

  // Merge with request-scoped context (requestId, userId)
  const store = requestContext?.getStore();
  const scopedContext = store
    ? { ...store, ...normalizedContext }
    : normalizedContext;

  const entry = {
    timestamp: formatTimestamp(),
    level,
    message,
    ...(scopedContext && Object.keys(scopedContext).length > 0 ? { context: scopedContext } : {}),
  };

  const formatted = JSON.stringify(entry);

  switch (level) {
    case "error":
      console.error(formatted);
      break;
    case "warn":
      console.warn(formatted);
      break;
    case "debug":
      if (process.env.NODE_ENV === "development") {
        console.log(formatted);
      }
      break;
    default:
      console.log(formatted);
  }
}

export const logger = {
  debug: (message: string, context?: LogContext | unknown) => log("debug", message, context),
  info: (message: string, context?: LogContext | unknown) => log("info", message, context),
  warn: (message: string, context?: LogContext | unknown) => log("warn", message, context),
  error: (message: string, context?: LogContext | unknown) => log("error", message, context),
};

/**
 * Create a child logger with a fixed context (e.g., module name).
 *
 * Usage:
 *   const log = logger.child({ module: "audit" });
 *   log.info("Starting audit", { auditId });
 */
export function createChildLogger(defaultContext: LogContext) {
  return {
    debug: (message: string, context?: LogContext) =>
      log("debug", message, { ...defaultContext, ...context }),
    info: (message: string, context?: LogContext) =>
      log("info", message, { ...defaultContext, ...context }),
    warn: (message: string, context?: LogContext) =>
      log("warn", message, { ...defaultContext, ...context }),
    error: (message: string, context?: LogContext) =>
      log("error", message, { ...defaultContext, ...context }),
  };
}
