import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Convención: identificadores con prefijo `_` son intencionalmente no usados
    // (params de handlers, destructures parciales, callbacks).
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    // Los tests construyen mocks parciales: `any` puntual es aceptable ahí,
    // pero no se permite que se propague a código de producción.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    files: [
      "src/server/intelligence/**/*.ts",
      "src/app/api/intelligence/**/*.ts",
      "src/app/api/bulk-scan/**/*.ts",
      "src/app/api/api-keys/**/*.ts",
      "src/app/api/monitoring/**/*.ts",
      "src/app/api/webhooks/**/*.ts",
      "src/features/dashboard/tabs/IntelligenceTab.tsx",
      "src/features/dashboard/tabs/MonitoringTab.tsx",
      "src/features/dashboard/tabs/SettingsTab.tsx",
      "src/features/dashboard/tabs/AdversaryTab.tsx",
      "src/features/intelligence/hooks/**/*.ts"
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
  {
    // UI components with intentional mount-time state patterns (fetch,
    // localStorage hydration, poll intervals, pulse animations).
    files: [
      "src/features/dashboard/tabs/MarketplaceTab.tsx",
      "src/features/dashboard/tabs/OverviewTab.tsx",
      "src/features/dashboard/CustomDashboardGrid.tsx",
      "src/features/dashboard/HistoryPanel.tsx",
      "src/features/dashboard/InstallPwaButton.tsx",
      "src/features/dashboard/LiveMetricsBar.tsx",
      "src/features/dashboard/ScoreGauge.tsx",
      "src/app/docs/api/playground/page.tsx",
      "src/app/settings/api-keys/ApiKeysDashboard.tsx"
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Trigger.dev — do NOT lint these:
    ".trigger/**",
    // Generated test artifacts (Playwright reports contain bundled/minified JS):
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    "e2e/**/*-snapshots/**",
    // SQL migration files — not JS/TS:
    "drizzle/**",
    // Vendored minified third-party bundles (mermaid, web-vitals):
    "docs/vendor/**",
    "public/vendor/**",
    // Development directories and scratch files
    "scratch/**",
    "backups/**",
    "configure-upstash-alerts.ts",
    "db-security-scan.ts",
    "rls-fire-test.ts",
    "test-rls-root.ts",
    "backup-manager.ts",
    "hello.ts",
  ]),
]);

export default eslintConfig;
