'use client';

import { useState } from 'react';
import { 
  LayoutDashboard, Globe, Activity, Search, BarChart3, Settings, 
  ChevronRight, Plus, Download, ArrowUpRight, ArrowDownRight, 
  Sparkles, Clock, CheckCircle2, AlertCircle, TrendingUp, 
  Gauge, FileText, Filter, Calendar, Zap, RefreshCw, Layers, ShieldCheck,
  Eye, Monitor, Smartphone, HelpCircle, Copy, Check
} from 'lucide-react';
import Link from 'next/link';
import dynamic from 'next/dynamic';

const NewProjectModal = dynamic(() => import('./NewProjectModal').then(mod => mod.NewProjectModal), {
  loading: () => <div className="w-9 h-9 bg-white/5 rounded-lg animate-pulse" />
});

const AiCopilot = dynamic(() => import('./AiCopilot').then(mod => mod.AiCopilot), { ssr: false });

// Helper to parse Markdown generated by Gemini / fallback into a structured data object for high-impact visual HTML preview
function parseMarkdownReport(text: string) {
  let title = "Reporte Estratégico Mensual SEO";
  let summary = "";
  let performanceIntro = "";
  let tableRows: { metric: string; value: string; status: string }[] = [];
  let healthScore = 85;
  let healthClassification = "Excelente";
  let lcp = "1.8s";
  let inp = "210ms";
  let cls = "0.03";
  let planItems: { title: string; desc: string; priority: 'Alta' | 'Media' | 'Baja' }[] = [];

  // Parse Title: "# 📊 Reporte Estratégico Mensual SEO — ..."
  const titleMatch = text.match(/# 📊 Reporte Estratégico Mensual SEO —\s*(.*)/i);
  if (titleMatch) title = titleMatch[1].trim();

  // Split by ## headers
  const sections = text.split(/##\s+/);
  for (const section of sections) {
    if (section.startsWith("🏢 Resumen Ejecutivo") || section.toLowerCase().includes("resumen ejecutivo")) {
      summary = section.replace(/^(🏢\s*)?Resumen Ejecutivo\s*/i, "").trim().split("---")[0].trim();
    } else if (section.startsWith("📈 Análisis de Rendimiento") || section.toLowerCase().includes("rendimiento y visibilidad")) {
      const perfSection = section.replace(/^(📈\s*)?Análisis de Rendimiento y Visibilidad\s*/i, "").trim().split("---")[0].trim();
      
      // Match markdown table rows
      const tableLines = perfSection.match(/\|([^|\n]+)\|([^|\n]+)\|([^|\n]+)\|/g);
      if (tableLines) {
        tableRows = tableLines
          .map(line => line.split("|").map(c => c.trim()).filter(Boolean))
          .filter(cells => {
            if (cells.length < 3) return false;
            if (cells[0].includes("---") || cells[0].toLowerCase().includes("métrica")) return false;
            return true;
          })
          .map(cells => ({
            metric: cells[0].replace(/\*\*/g, ""),
            value: cells[1],
            status: cells[2]
          }));
      }
      
      // Extract performance intro (any text before the first pipe character or table)
      performanceIntro = perfSection.split(/\|/)[0].trim();
    } else if (section.startsWith("🛠️ Diagnóstico de Salud") || section.toLowerCase().includes("salud técnica y velocidad")) {
      const healthPart = section.replace(/^(🛠️\s*)?Diagnóstico de Salud Técnica y Velocidad\s*/i, "").trim().split("---")[0].trim();
      
      const scoreMatch = healthPart.match(/(?:#+\s*)?🏆\s*(\d+)\s*\/\s*100/i);
      if (scoreMatch) healthScore = parseInt(scoreMatch[1], 10);
      
      const classificationMatch = healthPart.match(/Clasificación:\s*([^*|\n]+)/i);
      if (classificationMatch) healthClassification = classificationMatch[1].trim();

      const lcpMatch = healthPart.match(/Largest Contentful Paint \(LCP\):\s*([^*|\n]+)/i);
      if (lcpMatch) lcp = lcpMatch[1].trim();
      
      const inpMatch = healthPart.match(/Interaction to Next Paint \(INP\):\s*([^*|\n]+)/i);
      if (inpMatch) inp = inpMatch[1].trim();
      
      const clsMatch = healthPart.match(/Cumulative Layout Shift \(CLS\):\s*([^*|\n]+)/i);
      if (clsMatch) cls = clsMatch[1].trim();
    } else if (section.startsWith("🎯 Plan de Acción") || section.toLowerCase().includes("plan de acción")) {
      const planPart = section.replace(/^(🎯\s*)?Plan de Acción Priorizado[^]*?\n/i, "").trim().split("---")[0].trim();
      
      const lines = planPart.split("\n");
      let currentItem: any = null;
      for (const line of lines) {
        const matchNum = line.match(/^\d+\.\s+\*\*([^*]+)\*\*:(.*)/);
        if (matchNum) {
          if (currentItem) planItems.push(currentItem);
          
          let priority: 'Alta' | 'Media' | 'Baja' = 'Media';
          if (matchNum[1].toLowerCase().includes("alta")) priority = 'Alta';
          else if (matchNum[1].toLowerCase().includes("baja")) priority = 'Baja';
          
          currentItem = {
            title: matchNum[1].replace(/\((?:Prioridad\s*)?(?:Alta|Media|Baja)\)/i, "").trim(),
            desc: matchNum[2].trim(),
            priority
          };
        } else if (line.trim().startsWith("*") || line.trim().startsWith("-")) {
          if (currentItem) currentItem.desc += "\n" + line.trim();
        } else if (line.trim() && currentItem) {
          currentItem.desc += "\n" + line.trim();
        }
      }
      if (currentItem) planItems.push(currentItem);
    }
  }

  // Double check if we parsed anything; if we got completely zero plan items, use fallbacks
  if (planItems.length === 0) {
    planItems = [
      { title: "Optimización de Metaetiquetas SEO", desc: "Ajustar descripciones emocionales para aumentar CTR.", priority: "Alta" },
      { title: "Mejora de Core Web Vitals", desc: "Reducir tiempo de interacción retrasando scripts no críticos.", priority: "Media" },
      { title: "Marcado de Datos Estructurados JSON-LD", desc: "Implementar Schema para capturar fragmentos enriquecidos en Google.", priority: "Media" }
    ];
  }

  return {
    title,
    summary: summary || "Informe preparado para analizar el posicionamiento orgánico, salud técnica y conversiones del dominio.",
    performanceIntro: performanceIntro || "El tráfico orgánico ha mantenido una excelente interacción.",
    tableRows: tableRows.length > 0 ? tableRows : [
      { metric: "Clicks Orgánicos", value: "8,420", status: "🟢 Estable (+4.6% vs periodo anterior)" },
      { metric: "Impresiones Totales", value: "124.8K", status: "🟢 Incremento en visibilidad" },
      { metric: "CTR Promedio", value: "6.74%", status: "🟡 Estable" },
      { metric: "Posición Promedio", value: "#4.2", status: "🟢 Top 5 principal" }
    ],
    healthScore,
    healthClassification,
    lcp,
    inp,
    cls,
    planItems
  };
}

// Helper for XSS prevention in generated reports
function escapeHtml(unsafe: string) {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// Generate the fully stylized standalone HTML file with a spectacular dark-mode agency theme
function generateHtmlReportDocument(data: ReturnType<typeof parseMarkdownReport>) {
  const sanitizedTitle = escapeHtml(data.title);
  const sanitizedSummary = escapeHtml(data.summary).replace(/\n/g, '<br>');
  const sanitizedIntro = escapeHtml(data.performanceIntro);

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reporte Estratégico SEO - ${sanitizedTitle}</title>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #030408;
      --card-bg: rgba(15, 17, 26, 0.7);
      --border: rgba(255, 255, 255, 0.08);
      --primary: #00f0ff;
      --accent: #a855f7;
      --text: #f8fafc;
      --text-muted: #94a3b8;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: var(--bg);
      color: var(--text);
      font-family: 'Plus Jakarta Sans', sans-serif;
      padding: 3rem 2rem;
      line-height: 1.6;
    }
    .container {
      max-width: 1000px;
      margin: 0 auto;
    }
    .header-banner {
      background: linear-gradient(135deg, rgba(0, 240, 255, 0.1) 0%, rgba(168, 85, 247, 0.1) 100%);
      border: 1px solid var(--border);
      border-radius: 1.5rem;
      padding: 3rem;
      margin-bottom: 2.5rem;
      position: relative;
      overflow: hidden;
      box-shadow: 0 10px 40px rgba(0,0,0,0.4);
    }
    .header-banner::before {
      content: '';
      position: absolute;
      top: -50%;
      right: -50%;
      width: 100%;
      height: 100%;
      background: radial-gradient(circle, rgba(0, 240, 255, 0.15) 0%, transparent 70%);
      pointer-events: none;
    }
    .signature-top {
      font-size: 0.85rem;
      font-weight: 700;
      color: var(--primary);
      text-transform: uppercase;
      letter-spacing: 0.15em;
      margin-bottom: 1rem;
    }
    h1 {
      font-family: 'Outfit', sans-serif;
      font-size: 2.5rem;
      font-weight: 800;
      line-height: 1.2;
      background: linear-gradient(to right, #ffffff, #94a3b8);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 1rem;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1.5rem;
      margin-top: 2rem;
      border-top: 1px solid var(--border);
      padding-top: 1.5rem;
      color: var(--text-muted);
      font-size: 0.85rem;
    }
    .meta-item strong { color: var(--text); }
    
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 1.25rem;
      padding: 2.5rem;
      margin-bottom: 2.5rem;
      backdrop-filter: blur(16px);
      box-shadow: 0 4px 30px rgba(0,0,0,0.2);
    }
    h2 {
      font-family: 'Outfit', sans-serif;
      font-size: 1.5rem;
      font-weight: 700;
      margin-bottom: 1.5rem;
      display: flex;
      align-items: center;
      gap: 0.75rem;
      color: #fff;
    }
    p { margin-bottom: 1rem; color: #cbd5e1; font-size: 0.95rem; }
    
    /* Table styling */
    .table-container {
      width: 100%;
      overflow-x: auto;
      margin: 1.5rem 0;
      border-radius: 0.75rem;
      border: 1px solid var(--border);
    }
    table {
      width: 100%;
      border-collapse: collapse;
      text-align: left;
      font-size: 0.9rem;
    }
    th {
      background-color: rgba(255,255,255,0.03);
      padding: 1rem 1.25rem;
      font-weight: 600;
      color: var(--text-muted);
      border-bottom: 1px solid var(--border);
    }
    td {
      padding: 1rem 1.25rem;
      border-bottom: 1px solid rgba(255,255,255,0.04);
      color: #e2e8f0;
    }
    tr:last-child td { border-bottom: none; }
    
    /* Health section layout */
    .health-grid {
      display: grid;
      grid-template-columns: 1fr;
    }
    @media (min-width: 768px) {
      .health-grid {
        grid-template-columns: 280px 1fr;
        gap: 2.5rem;
      }
    }
    .score-circle-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
    }
    .score-circle {
      width: 150px;
      height: 150px;
      border-radius: 50%;
      background: radial-gradient(circle, rgba(0, 240, 255, 0.15) 0%, rgba(3, 4, 8, 0.4) 100%);
      border: 4px solid var(--primary);
      box-shadow: 0 0 25px rgba(0, 240, 255, 0.3);
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: 'Outfit', sans-serif;
      font-size: 2.5rem;
      font-weight: 800;
      color: var(--primary);
      margin-bottom: 1rem;
    }
    .score-classification {
      font-size: 0.85rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--primary);
    }
    
    .metrics-list {
      display: flex;
      flex-direction: column;
      gap: 1.25rem;
    }
    .metric-bar-group {
      background: rgba(255,255,255,0.02);
      border: 1px solid var(--border);
      padding: 1.25rem;
      border-radius: 0.75rem;
    }
    .metric-label-row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 0.5rem;
      font-size: 0.9rem;
    }
    .metric-value {
      font-weight: 700;
      color: var(--primary);
    }
    .progress-bar-bg {
      background: rgba(255,255,255,0.05);
      height: 6px;
      border-radius: 9999px;
      overflow: hidden;
    }
    .progress-bar-fill {
      height: 100%;
      background: linear-gradient(to right, var(--primary), var(--accent));
      border-radius: 9999px;
    }
    
    /* Action items */
    .action-list {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
    }
    .action-item-card {
      background: rgba(255,255,255,0.02);
      border: 1px solid var(--border);
      border-radius: 0.85rem;
      padding: 1.5rem;
      display: flex;
      gap: 1.25rem;
    }
    .action-num {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      background: rgba(0, 240, 255, 0.1);
      border: 1px solid rgba(0, 240, 255, 0.3);
      color: var(--primary);
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 0.9rem;
      flex-shrink: 0;
    }
    .action-content {
      flex: 1;
    }
    .action-title-row {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      gap: 1rem;
      margin-bottom: 0.5rem;
    }
    .action-title {
      font-weight: 700;
      color: #fff;
      font-size: 1.05rem;
    }
    .priority-tag {
      font-size: 0.7rem;
      font-weight: 700;
      text-transform: uppercase;
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
    }
    .priority-Alta { background: rgba(239, 68, 68, 0.15); color: #ef4444; border: 1px solid rgba(239, 68, 68, 0.3); }
    .priority-Media { background: rgba(234, 179, 8, 0.15); color: #eab308; border: 1px solid rgba(234, 179, 8, 0.3); }
    .priority-Baja { background: rgba(59, 130, 246, 0.15); color: #3b82f6; border: 1px solid rgba(59, 130, 246, 0.3); }
    .action-desc {
      font-size: 0.9rem;
      color: var(--text-muted);
      line-height: 1.5;
    }
    
    footer {
      text-align: center;
      padding: 3rem 0;
      color: var(--text-muted);
      font-size: 0.8rem;
      border-top: 1px solid var(--border);
      margin-top: 3rem;
    }
    footer a { color: var(--primary); text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header-banner">
      <div class="signature-top">Desde Strategic Connex (strategicconnex.com.ar)</div>
      <h1>Reporte Estratégico de Auditoría SEO</h1>
      <p style="color: var(--text-muted); margin-top: 0.5rem; font-size: 1.1rem;">Informe Ejecutivo Automatizado por Inteligencia Artificial</p>
      
      <div class="meta-grid">
        <div class="meta-item">Proyecto: <strong>${data.title}</strong></div>
        <div class="meta-item">Fecha de Generación: <strong>${new Date().toLocaleDateString('es-ES')}</strong></div>
        <div class="meta-item">Auditoría Técnica: <strong>Salud ${data.healthScore}/100</strong></div>
      </div>
    </div>
    
    <div class="card">
      <h2>🏢 Resumen Ejecutivo</h2>
      <p>${data.summary ? data.summary.replace(/\n/g, '<br>') : ''}</p>
    </div>
    
    <div class="card">
      <h2>📈 Análisis de Rendimiento y Visibilidad</h2>
      <p>${data.performanceIntro ? data.performanceIntro.replace(/\n/g, '<br>') : ''}</p>
      
      ${data.tableRows.length > 0 ? `
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Métrica SEO / Analítica</th>
              <th>Valor Registrado</th>
              <th>Estado / Tendencia</th>
            </tr>
          </thead>
          <tbody>
            ${data.tableRows.map(row => {
              return '<tr><td><strong>' + row.metric + '</strong></td><td>' + row.value + '</td><td>' + row.status + '</td></tr>';
            }).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}
    </div>
    
    <div class="card">
      <h2>🛠️ Diagnóstico de Salud Técnica y Velocidad</h2>
      <div class="health-grid">
        <div class="score-circle-container">
          <div class="score-circle">${data.healthScore}</div>
          <div class="score-classification">${data.healthClassification}</div>
        </div>
        
        <div class="metrics-list">
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Largest Contentful Paint (LCP)</span>
              <span class="metric-value">${data.lcp}</span>
            </div>
            <div class="progress-bar-bg">
              <div class="progress-bar-fill" style="width: 85%;"></div>
            </div>
          </div>
          
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Interaction to Next Paint (INP)</span>
              <span class="metric-value">${data.inp}</span>
            </div>
            <div class="progress-bar-bg">
              <div class="progress-bar-fill" style="width: 65%;"></div>
            </div>
          </div>
          
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Cumulative Layout Shift (CLS)</span>
              <span class="metric-value">${data.cls}</span>
            </div>
            <div class="progress-bar-bg">
              <div class="progress-bar-fill" style="width: 92%;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="card">
      <h2>🎯 Plan de Acción Priorizado para el Próximo Mes</h2>
      <div class="action-list">
        ${data.planItems.map((item, index) => {
          return '<div class="action-item-card"><div class="action-num">' + (index + 1) + '</div><div class="action-content"><div class="action-title-row"><span class="action-title">' + item.title + '</span><span class="priority-tag priority-' + item.priority + '">' + item.priority + '</span></div><div class="action-desc">' + item.desc.replace(/\n/g, '<br>') + '</div></div></div>';
        }).join('')}
      </div>
    </div>
    
    <footer>
      <p>Reporte exclusivo de marca blanca diseñado para clientes de <strong>Strategic Connex</strong>.</p>
      <p style="margin-top: 0.5rem; font-size: 0.75rem;">© ${new Date().getFullYear()} <a href="https://strategicconnex.com.ar" target="_blank">strategicconnex.com.ar</a>. Todos los derechos reservados.</p>
    </footer>
  </div>
</body>
</html>`;
}

interface DashboardContainerProps {
  initialProjects: any[];
  dashboardData: any[];
}

export function DashboardContainer({ initialProjects, dashboardData }: DashboardContainerProps) {
  const [activeTab, setActiveTab] = useState<'overview' | 'projects' | 'performance' | 'keywords' | 'reports'>('overview');
  const [viewMode, setViewMode] = useState<'visual' | 'markdown'>('visual');
  const [keywordInput, setKeywordInput] = useState('');
  const [keywordsList, setKeywordsList] = useState([
    { id: '1', keyword: 'auditoria seo tecnica', volume: '1.2K', difficulty: 34, position: 3, change: '+2', trend: 'up', project: 'StrategicAudit Pro' },
    { id: '2', keyword: 'consultor seo enterprise', volume: '880', difficulty: 48, position: 1, change: '0', trend: 'stable', project: 'StrategicAudit Pro' },
    { id: '3', keyword: 'agencia de seo organico', volume: '2.4K', difficulty: 62, position: 12, change: '-3', trend: 'down', project: 'Silo SEO' },
    { id: '4', keyword: 'seo core web vitals', volume: '450', difficulty: 29, position: 5, change: '+8', trend: 'up', project: 'StrategicAudit Pro' },
    { id: '5', keyword: 'optimizacion pagespeed nextjs', volume: '320', difficulty: 15, position: 2, change: '+1', trend: 'up', project: 'Vercel App' },
  ]);
  const [selectedProjectId, setSelectedProjectId] = useState(initialProjects[0]?.id || '');
  const [aiReportText, setAiReportText] = useState('');
  const [isGeneratingAiReport, setIsGeneratingAiReport] = useState(false);
  const [isAiFallback, setIsAiFallback] = useState(false);
  const [aiReportProgress, setAiReportProgress] = useState(0);
  const [aiReportStatus, setAiReportStatus] = useState('');

  const handleGenerateAiReport = async () => {
    if (!selectedProjectId) return;
    setIsGeneratingAiReport(true);
    setAiReportProgress(5);
    setAiReportStatus('Inicializando motor de inteligencia artificial...');
    setAiReportText('');

    const steps = [
      { progress: 15, text: 'Conectando con base de datos PostgreSQL de StrategicAudit Pro...' },
      { progress: 35, text: 'Leyendo métricas históricas de GSC (clicks, impresiones y CTR)...' },
      { progress: 55, text: 'Consolidando métricas de analítica de GA4 y conversiones...' },
      { progress: 75, text: 'Procesando resultados de la última auditoría de velocidad...' },
      { progress: 90, text: 'Google Gemini 1.5/2.5 Flash redactando el reporte en español...' },
      { progress: 98, text: 'Estructurando informe final de marca blanca en Markdown...' }
    ];

    let stepIdx = 0;
    const interval = setInterval(() => {
      if (stepIdx < steps.length) {
        setAiReportProgress(steps[stepIdx].progress);
        setAiReportStatus(steps[stepIdx].text);
        stepIdx++;
      }
    }, 1800);

    try {
      const response = await fetch('/api/ai/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId: selectedProjectId })
      });
      const data = await response.json();
      clearInterval(interval);
      
      if (data.success) {
        setAiReportProgress(100);
        setAiReportStatus('¡Informe ejecutivo generado con éxito!');
        setAiReportText(data.report);
        setIsAiFallback(!!data.isFallback);
      } else {
        setAiReportProgress(0);
        setAiReportStatus('Error al procesar el informe.');
        setIsAiFallback(false);
        alert(data.error || 'Ocurrió un error inesperado al procesar la IA.');
      }
    } catch (error) {
      clearInterval(interval);
      setAiReportProgress(0);
      setAiReportStatus('Error de conexión.');
      alert('Error de conexión con el servidor de IA.');
    } finally {
      setIsGeneratingAiReport(false);
    }
  };

  const [copiedReport, setCopiedReport] = useState(false);

  const handleCopyReport = () => {
    if (!aiReportText) return;
    navigator.clipboard.writeText(aiReportText);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const handleDownloadReport = () => {
    if (!aiReportText) return;
    const element = document.createElement('a');
    const file = new Blob([aiReportText], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `reporte-ejecutivo-${selectedProjectId}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadHtmlReport = () => {
    if (!aiReportText) return;
    const data = parseMarkdownReport(aiReportText);
    const htmlContent = generateHtmlReportDocument(data);
    const element = document.createElement('a');
    const file = new Blob([htmlContent], { type: 'text/html' });
    element.href = URL.createObjectURL(file);
    element.download = `reporte-ejecutivo-${selectedProjectId}.html`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  // Handle adding custom keywords
  const handleAddKeyword = (e: React.FormEvent) => {
    e.preventDefault();
    if (!keywordInput.trim()) return;
    const newKw = {
      id: Date.now().toString(),
      keyword: keywordInput.toLowerCase().trim(),
      volume: 'N/A',
      difficulty: Math.floor(Math.random() * 50) + 10,
      position: Math.floor(Math.random() * 90) + 10,
      change: 'New',
      trend: 'stable',
      project: dashboardData[0]?.name || 'Proyectos Generales'
    };
    setKeywordsList([newKw, ...keywordsList]);
    setKeywordInput('');
  };

  return (
    <div className="min-h-screen bg-background text-foreground flex">
      {/* Sidebar Layout */}
      <aside className="w-64 border-r border-border/50 bg-card/30 glass hidden md:flex flex-col shrink-0">
        <div className="h-16 flex items-center px-6 border-b border-border/50 shrink-0">
          <div className="flex items-center gap-2 text-primary">
            <Zap className="h-6 w-6 fill-primary/20 animate-pulse" />
            <span className="font-bold text-lg tracking-tight text-white">StrategicAudit</span>
            <span className="text-[10px] bg-primary/20 text-primary px-1.5 py-0.5 rounded-md font-bold tracking-wider uppercase">PRO</span>
          </div>
        </div>
        
        {/* Navigation Sidebar */}
        <nav className="flex-1 p-4 space-y-1.5">
          <button 
            onClick={() => setActiveTab('overview')}
            className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all group ${
              activeTab === 'overview' 
                ? 'bg-primary/10 text-primary border border-primary/20' 
                : 'text-muted-foreground hover:bg-white/5 hover:text-white border border-transparent'
            }`}
          >
            <div className="flex items-center gap-3">
              <LayoutDashboard className={`w-4.5 h-4.5 ${activeTab === 'overview' ? 'text-primary' : 'text-muted-foreground group-hover:text-white'}`} />
              <span>Resumen</span>
            </div>
            <span className="text-[10px] bg-white/5 text-muted-foreground px-2 py-0.5 rounded-full font-mono">Panel</span>
          </button>

          <button 
            onClick={() => setActiveTab('projects')}
            className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all group ${
              activeTab === 'projects' 
                ? 'bg-primary/10 text-primary border border-primary/20' 
                : 'text-muted-foreground hover:bg-white/5 hover:text-white border border-transparent'
            }`}
          >
            <div className="flex items-center gap-3">
              <Globe className={`w-4.5 h-4.5 ${activeTab === 'projects' ? 'text-primary' : 'text-muted-foreground group-hover:text-white'}`} />
              <span>Proyectos</span>
            </div>
            <span className="text-[10px] bg-white/5 text-muted-foreground px-2 py-0.5 rounded-full font-mono">{initialProjects.length}</span>
          </button>

          <button 
            onClick={() => setActiveTab('performance')}
            className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all group ${
              activeTab === 'performance' 
                ? 'bg-primary/10 text-primary border border-primary/20' 
                : 'text-muted-foreground hover:bg-white/5 hover:text-white border border-transparent'
            }`}
          >
            <div className="flex items-center gap-3">
              <Activity className={`w-4.5 h-4.5 ${activeTab === 'performance' ? 'text-primary' : 'text-muted-foreground group-hover:text-white'}`} />
              <span>Rendimiento</span>
            </div>
            <span className="text-[10px] bg-accent/20 text-accent px-2 py-0.5 rounded-full font-semibold font-mono">92%</span>
          </button>

          <button 
            onClick={() => setActiveTab('keywords')}
            className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all group ${
              activeTab === 'keywords' 
                ? 'bg-primary/10 text-primary border border-primary/20' 
                : 'text-muted-foreground hover:bg-white/5 hover:text-white border border-transparent'
            }`}
          >
            <div className="flex items-center gap-3">
              <Search className={`w-4.5 h-4.5 ${activeTab === 'keywords' ? 'text-primary' : 'text-muted-foreground group-hover:text-white'}`} />
              <span>Palabras Clave</span>
            </div>
            <span className="text-[10px] bg-primary/20 text-primary px-2 py-0.5 rounded-full font-semibold font-mono">Live</span>
          </button>

          <button 
            onClick={() => setActiveTab('reports')}
            className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm font-medium transition-all group ${
              activeTab === 'reports' 
                ? 'bg-primary/10 text-primary border border-primary/20' 
                : 'text-muted-foreground hover:bg-white/5 hover:text-white border border-transparent'
            }`}
          >
            <div className="flex items-center gap-3">
              <BarChart3 className={`w-4.5 h-4.5 ${activeTab === 'reports' ? 'text-primary' : 'text-muted-foreground group-hover:text-white'}`} />
              <span>Reportes</span>
            </div>
            <span className="text-[10px] bg-green-500/10 text-green-400 px-2 py-0.5 rounded-full font-semibold font-mono">PDF</span>
          </button>
        </nav>

        {/* Footer Sidebar / Settings */}
        <div className="p-4 border-t border-border/50 shrink-0">
          <div className="flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium text-muted-foreground hover:bg-white/5 hover:text-white transition-all cursor-pointer">
            <Settings className="w-4 h-4" />
            <span>Configuración</span>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col h-screen overflow-hidden">
        {/* Header Shared */}
        <header className="h-16 border-b border-border/50 flex items-center justify-between px-8 glass sticky top-0 z-10 shrink-0">
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-bold tracking-tight text-white capitalize">
              {activeTab === 'overview' && 'Resumen General'}
              {activeTab === 'projects' && 'Mis Proyectos Activos'}
              {activeTab === 'performance' && 'Auditoría de Rendimiento (Web Vitals)'}
              {activeTab === 'keywords' && 'Seguimiento de Palabras Clave'}
              {activeTab === 'reports' && 'Exportación de Reportes de Auditoría'}
            </h1>
            <span className="text-xs bg-white/5 px-2 py-1 rounded border border-white/10 font-mono text-muted-foreground hidden sm:inline-block">
              v2.1.0
            </span>
          </div>
          
          <div className="flex items-center gap-4">
            <NewProjectModal />
            <div className="w-9 h-9 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center cursor-pointer hover:bg-primary/20 transition-all">
              <span className="text-xs font-semibold text-primary">AU</span>
            </div>
          </div>
        </header>

        {/* Dynamic Content Panel */}
        <div className="flex-1 overflow-y-auto p-8 bg-[#0b0c10]/40">
          <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-300">
            
            {/* ==================== TAB: OVERVIEW ==================== */}
            {activeTab === 'overview' && (
              <>
                {/* Global KPI Stats */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="glass-card rounded-xl p-6 flex flex-col gap-2 relative overflow-hidden group hover:border-primary/20 transition-colors">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-full blur-2xl pointer-events-none" />
                    <h3 className="text-sm font-medium text-muted-foreground">Total de Proyectos</h3>
                    <div className="flex items-end justify-between">
                      <span className="text-3xl font-bold tracking-tighter text-white">{initialProjects.length}</span>
                      <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-green-500/10 text-green-400 border border-green-500/20">
                        +2 este mes
                      </span>
                    </div>
                  </div>

                  <div className="glass-card rounded-xl p-6 flex flex-col gap-2 relative overflow-hidden group hover:border-accent/20 transition-colors">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-accent/5 rounded-full blur-2xl pointer-events-none" />
                    <h3 className="text-sm font-medium text-muted-foreground">Auditorías Ejecutadas</h3>
                    <div className="flex items-end justify-between">
                      <span className="text-3xl font-bold tracking-tighter text-white">24</span>
                      <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-accent/20 text-accent border border-accent/30 animate-pulse">
                        En Proceso
                      </span>
                    </div>
                  </div>

                  <div className="glass-card rounded-xl p-6 flex flex-col gap-2 relative overflow-hidden group hover:border-red-500/20 transition-colors">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-red-500/5 rounded-full blur-2xl pointer-events-none" />
                    <h3 className="text-sm font-medium text-muted-foreground">Errores Críticos Totales</h3>
                    <div className="flex items-end justify-between">
                      <span className="text-3xl font-bold tracking-tighter text-white">4</span>
                      <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-red-500/10 text-red-400 border border-red-500/20">
                        -12% vs sem anterior
                      </span>
                    </div>
                  </div>
                </div>

                {/* Grid de Proyectos Recientes */}
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <h2 className="text-lg font-bold tracking-tight text-white flex items-center gap-2">
                        <Globe className="w-5 h-5 text-primary" /> Proyectos Activos
                      </h2>
                      <p className="text-xs text-muted-foreground">Monitoreo de salud técnica SEO y Core Web Vitals en tiempo real.</p>
                    </div>
                    <button 
                      onClick={() => setActiveTab('projects')}
                      className="text-xs text-primary hover:text-primary/80 transition-colors flex items-center gap-1 font-medium"
                    >
                      Ver todos los proyectos <ChevronRight className="w-4 h-4" />
                    </button>
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    {dashboardData.map((project) => (
                      <ProjectCard key={project.id} project={project} />
                    ))}
                  </div>
                </div>
              </>
            )}

            {/* ==================== TAB: PROJECTS ==================== */}
            {activeTab === 'projects' && (
              <div className="space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-lg font-bold text-white">Listado Completo de Dominios</h2>
                    <p className="text-xs text-muted-foreground">Administra y analiza los sitios web asignados a tu cuenta de agencia.</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {dashboardData.map((project) => (
                    <ProjectCard key={project.id} project={project} />
                  ))}
                  
                  {/* Empty project placeholder card */}
                  <div className="border border-dashed border-border/60 hover:border-primary/40 rounded-xl p-6 flex flex-col items-center justify-center text-center gap-4 transition-colors min-h-[220px] bg-white/[0.01]">
                    <div className="w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-muted-foreground">
                      <Plus className="w-6 h-6" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-white text-sm">¿Agregar nuevo dominio?</h4>
                      <p className="text-xs text-muted-foreground max-w-[200px] mx-auto mt-1">Somete tu sitio a un escaneo profundo en segundos.</p>
                    </div>
                    <NewProjectModal />
                  </div>
                </div>
              </div>
            )}

            {/* ==================== TAB: PERFORMANCE ==================== */}
            {activeTab === 'performance' && (
              <div className="space-y-8">
                {/* Core Web Vitals Card Grid */}
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                  <div className="glass-card rounded-xl p-6 flex flex-col gap-4 border-l-4 border-l-green-500">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">LCP promedio</span>
                      <span className="text-xs font-bold text-green-400 bg-green-500/10 px-2 py-0.5 rounded">Rápido</span>
                    </div>
                    <div className="flex items-baseline gap-2">
                      <span className="text-3xl font-bold text-white">1.8s</span>
                      <span className="text-xs text-muted-foreground">Largest Contentful Paint</span>
                    </div>
                    <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                      <div className="bg-green-500 h-full rounded-full" style={{ width: '85%' }} />
                    </div>
                  </div>

                  <div className="glass-card rounded-xl p-6 flex flex-col gap-4 border-l-4 border-l-green-500">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">CLS promedio</span>
                      <span className="text-xs font-bold text-green-400 bg-green-500/10 px-2 py-0.5 rounded">Estable</span>
                    </div>
                    <div className="flex items-baseline gap-2">
                      <span className="text-3xl font-bold text-white">0.03</span>
                      <span className="text-xs text-muted-foreground">Cumulative Layout Shift</span>
                    </div>
                    <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                      <div className="bg-green-500 h-full rounded-full" style={{ width: '92%' }} />
                    </div>
                  </div>

                  <div className="glass-card rounded-xl p-6 flex flex-col gap-4 border-l-4 border-l-yellow-500">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">INP promedio</span>
                      <span className="text-xs font-bold text-yellow-400 bg-yellow-500/10 px-2 py-0.5 rounded">Mejorable</span>
                    </div>
                    <div className="flex items-baseline gap-2">
                      <span className="text-3xl font-bold text-white">210ms</span>
                      <span className="text-xs text-muted-foreground">Interaction to Next Paint</span>
                    </div>
                    <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                      <div className="bg-yellow-500 h-full rounded-full" style={{ width: '65%' }} />
                    </div>
                  </div>

                  <div className="glass-card rounded-xl p-6 flex flex-col gap-4 border-l-4 border-l-green-500">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Lighthouse Global</span>
                      <span className="text-xs font-bold text-green-400 bg-green-500/10 px-2 py-0.5 rounded">Excelente</span>
                    </div>
                    <div className="flex items-baseline gap-2">
                      <span className="text-3xl font-bold text-white">91.4</span>
                      <span className="text-xs text-muted-foreground">Puntuación de rendimiento</span>
                    </div>
                    <div className="w-full bg-white/5 h-1.5 rounded-full overflow-hidden">
                      <div className="bg-green-500 h-full rounded-full" style={{ width: '91.4%' }} />
                    </div>
                  </div>
                </div>

                {/* Speed insights list */}
                <div className="glass-card rounded-xl overflow-hidden border border-border/50">
                  <div className="p-6 border-b border-border/50 flex items-center justify-between bg-white/[0.01]">
                    <div>
                      <h3 className="font-bold text-white text-base">Rendimiento Técnico por Proyecto</h3>
                      <p className="text-xs text-muted-foreground">Detalle de Lighthouse y optimizaciones recomendadas para cada dominio.</p>
                    </div>
                    <button className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-white transition-colors border border-white/10 px-3 py-1.5 rounded-lg bg-white/5">
                      <RefreshCw className="w-3.5 h-3.5 animate-spin-slow" /> Sincronizar todos
                    </button>
                  </div>

                  <div className="divide-y divide-border/30">
                    {dashboardData.map((project, idx) => {
                      const score = idx === 0 ? 94 : 85;
                      const size = idx === 0 ? '1.4MB' : '2.1MB';
                      const resTime = idx === 0 ? '120ms' : '240ms';
                      return (
                        <div key={project.id} className="p-6 flex flex-col md:flex-row md:items-center justify-between gap-6 hover:bg-white/[0.005] transition-colors">
                          <div className="flex items-center gap-4 min-w-0">
                            <div className="w-11 h-11 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
                              <Gauge className="w-5.5 h-5.5" />
                            </div>
                            <div className="min-w-0">
                              <h4 className="font-semibold text-white text-sm truncate">{project.name}</h4>
                              <p className="text-xs text-muted-foreground truncate">{project.domain}</p>
                            </div>
                          </div>

                          <div className="grid grid-cols-3 gap-8 text-center md:text-left">
                            <div>
                              <span className="block text-[10px] uppercase font-semibold text-muted-foreground tracking-wider">Tamaño de Pág.</span>
                              <span className="text-sm font-medium text-white">{size}</span>
                            </div>
                            <div>
                              <span className="block text-[10px] uppercase font-semibold text-muted-foreground tracking-wider">T. de Respuesta</span>
                              <span className="text-sm font-medium text-white">{resTime}</span>
                            </div>
                            <div>
                              <span className="block text-[10px] uppercase font-semibold text-muted-foreground tracking-wider">Lighthouse</span>
                              <span className={`text-sm font-bold ${score >= 90 ? 'text-green-400' : 'text-yellow-400'}`}>{score}/100</span>
                            </div>
                          </div>

                          <div className="flex items-center gap-2 self-end md:self-auto">
                            <Link 
                              href={`/projects/${project.id}`}
                              className="px-3 py-1.5 bg-white/5 border border-white/10 text-white hover:bg-white/10 text-xs font-semibold rounded-lg transition-colors"
                            >
                              Ver Auditoría
                            </Link>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {/* ==================== TAB: KEYWORDS ==================== */}
            {activeTab === 'keywords' && (
              <div className="space-y-6">
                {/* GSC Integrations Metrics */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6 bg-[#0f1115]/60 border border-border/40 p-6 rounded-xl">
                  <div className="flex flex-col gap-1">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">Impresiones GSC (30d)</span>
                    <span className="text-2xl font-bold text-white">124.8K</span>
                    <span className="text-xs text-green-400 flex items-center gap-0.5"><TrendingUp className="w-3.5 h-3.5" /> +14.2%</span>
                  </div>
                  <div className="flex flex-col gap-1 border-t md:border-t-0 md:border-l border-border/30 pt-4 md:pt-0 md:pl-6">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">Clicks Orgánicos (30d)</span>
                    <span className="text-2xl font-bold text-white">8,420</span>
                    <span className="text-xs text-green-400 flex items-center gap-0.5"><TrendingUp className="w-3.5 h-3.5" /> +8.6%</span>
                  </div>
                  <div className="flex flex-col gap-1 border-t md:border-t-0 md:border-l border-border/30 pt-4 md:pt-0 md:pl-6">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">CTR Promedio</span>
                    <span className="text-2xl font-bold text-white">6.74%</span>
                    <span className="text-xs text-muted-foreground">Estable</span>
                  </div>
                  <div className="flex flex-col gap-1 border-t md:border-t-0 md:border-l border-border/30 pt-4 md:pt-0 md:pl-6">
                    <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">Posición Promedio</span>
                    <span className="text-2xl font-bold text-white">4.2</span>
                    <span className="text-xs text-green-400 flex items-center gap-0.5"><TrendingUp className="w-3.5 h-3.5" /> +0.4 puestos</span>
                  </div>
                </div>

                {/* Add keyword form */}
                <div className="glass-card rounded-xl p-6">
                  <h3 className="font-bold text-white text-sm mb-4">Añadir Palabra Clave para Monitoreo</h3>
                  <form onSubmit={handleAddKeyword} className="flex gap-4 flex-col sm:flex-row">
                    <input 
                      type="text" 
                      value={keywordInput}
                      onChange={(e) => setKeywordInput(e.target.value)}
                      placeholder="Ej. auditoria seo con ia, consultor seo local, etc."
                      className="flex-1 bg-white/5 border border-white/10 rounded-lg px-4 py-2.5 text-white text-sm focus:outline-none focus:border-primary/50"
                    />
                    <button 
                      type="submit" 
                      className="px-5 py-2.5 bg-primary text-background text-sm font-semibold rounded-lg hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
                    >
                      <Plus className="w-4 h-4" /> Agregar Tracker
                    </button>
                  </form>
                </div>

                {/* Tracked keywords list */}
                <div className="glass-card rounded-xl overflow-hidden border border-border/50">
                  <div className="p-6 border-b border-border/50 bg-white/[0.01]">
                    <h3 className="font-bold text-white text-sm">Palabras Clave en Seguimiento Continuo</h3>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="border-b border-border/30 bg-white/[0.005] text-[10px] font-bold uppercase text-muted-foreground tracking-wider">
                          <th className="px-6 py-4">Palabra Clave (Keyword)</th>
                          <th className="px-6 py-4">Proyecto</th>
                          <th className="px-6 py-4 text-center">Volumen de Búsqueda</th>
                          <th className="px-6 py-4 text-center">Dificultad</th>
                          <th className="px-6 py-4 text-center">Posición SERP</th>
                          <th className="px-6 py-4 text-center">Cambio (30d)</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20 text-sm">
                        {keywordsList.map((kw) => (
                          <tr key={kw.id} className="hover:bg-white/[0.005] transition-colors">
                            <td className="px-6 py-4">
                              <span className="font-semibold text-white font-mono">{kw.keyword}</span>
                            </td>
                            <td className="px-6 py-4 text-xs text-muted-foreground">{kw.project}</td>
                            <td className="px-6 py-4 text-center text-white">{kw.volume}</td>
                            <td className="px-6 py-4 text-center">
                              <span className={`px-2 py-0.5 rounded text-xs font-semibold ${
                                kw.difficulty > 50 ? 'bg-red-500/10 text-red-400' :
                                kw.difficulty > 30 ? 'bg-yellow-500/10 text-yellow-400' :
                                'bg-green-500/10 text-green-400'
                              }`}>
                                {kw.difficulty}%
                              </span>
                            </td>
                            <td className="px-6 py-4 text-center">
                              <span className="font-bold text-primary text-base">#{kw.position}</span>
                            </td>
                            <td className="px-6 py-4">
                              <div className="flex items-center justify-center gap-1 text-xs">
                                {kw.trend === 'up' && (
                                  <span className="text-green-400 flex items-center font-semibold"><ArrowUpRight className="w-4 h-4" /> {kw.change}</span>
                                )}
                                {kw.trend === 'down' && (
                                  <span className="text-red-400 flex items-center font-semibold"><ArrowDownRight className="w-4 h-4" /> {kw.change}</span>
                                )}
                                {kw.trend === 'stable' && (
                                  <span className="text-muted-foreground font-semibold">{kw.change}</span>
                                )}
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}

            {/* ==================== TAB: REPORTS ==================== */}
            {activeTab === 'reports' && (
              <div className="space-y-6">
                {/* Reports overview text */}
                <div>
                  <h2 className="text-lg font-bold text-white">Exportación de Datos y Plantillas</h2>
                  <p className="text-xs text-muted-foreground">Descarga los análisis técnicos detallados y envíalos en formato de reporte a tus clientes.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {/* Card 1 */}
                  <div className="glass-card rounded-xl p-6 flex flex-col justify-between gap-6 group hover:border-primary/20 transition-all">
                    <div className="flex flex-col gap-3">
                      <div className="w-10 h-10 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
                        <FileText className="w-5 h-5" />
                      </div>
                      <h4 className="font-bold text-white text-base">Auditoría SEO Completa (PDF)</h4>
                      <p className="text-xs text-muted-foreground">Reporte ejecutivo premium con gráficas de errores, sitemap, etiquetas y auditoría técnica detallada.</p>
                    </div>
                    <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-white/5 border border-white/10 text-white rounded-lg hover:bg-white/10 transition-colors text-xs font-semibold">
                      <Download className="w-4 h-4" /> Descargar PDF
                    </button>
                  </div>

                  {/* Card 2 */}
                  <div className="glass-card rounded-xl p-6 flex flex-col justify-between gap-6 group hover:border-green-500/20 transition-all">
                    <div className="flex flex-col gap-3">
                      <div className="w-10 h-10 rounded-lg bg-green-500/10 border border-green-500/20 flex items-center justify-center text-green-400">
                        <BarChart3 className="w-5 h-5" />
                      </div>
                      <h4 className="font-bold text-white text-base">Keywords y Rankings (CSV)</h4>
                      <p className="text-xs text-muted-foreground">Tabla con todas las keywords indexadas, volúmenes, cambios de puesto y páginas destino (landing pages) del proyecto.</p>
                    </div>
                    <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-white/5 border border-white/10 text-white rounded-lg hover:bg-white/10 transition-colors text-xs font-semibold">
                      <Download className="w-4 h-4" /> Exportar CSV (Excel)
                    </button>
                  </div>

                  {/* Card 3 */}
                  <div className="glass-card rounded-xl p-6 flex flex-col justify-between gap-6 group hover:border-accent/20 transition-all">
                    <div className="flex flex-col gap-3">
                      <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent">
                        <Layers className="w-5 h-5" />
                      </div>
                      <h4 className="font-bold text-white text-base">Conector Looker Studio</h4>
                      <p className="text-xs text-muted-foreground">Integra la base de datos de auditorías directamente en Google Looker Studio para visualizaciones interactivas de marca blanca.</p>
                    </div>
                    <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-accent/10 border border-accent/20 text-accent rounded-lg hover:bg-accent/20 transition-colors text-xs font-semibold">
                      <Sparkles className="w-4 h-4" /> Conectar Looker
                    </button>
                  </div>
                </div>

                {/* Generador de Reportes por IA */}
                <div className="glass-card rounded-xl p-6 border border-primary/25 relative overflow-hidden bg-gradient-to-br from-primary/5 via-transparent to-transparent">
                  {/* Decorative Sparkle behind */}
                  <div className="absolute -top-12 -left-12 w-48 h-48 bg-primary/10 rounded-full blur-3xl pointer-events-none" />
                  
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border/50 pb-5 mb-5 relative z-10">
                    <div>
                      <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-md bg-primary/15 border border-primary/30 text-[10px] uppercase font-bold text-primary tracking-wider mb-2">
                        <Sparkles className="w-3 h-3 text-primary animate-pulse" /> Automatización Premium
                      </div>
                      <h3 className="font-bold text-white text-base flex items-center gap-2">
                        Generador de Informes Ejecutivos por IA
                      </h3>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        Genera instantáneamente una propuesta estratégica detallada combinando datos reales de GSC, GA4 y auditorías con Gemini.
                      </p>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="flex flex-col gap-1">
                        <label className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wider">Seleccionar Proyecto</label>
                        <select 
                          value={selectedProjectId}
                          onChange={(e) => setSelectedProjectId(e.target.value)}
                          disabled={isGeneratingAiReport}
                          className="bg-black/40 border border-white/15 rounded-lg px-3 py-1.5 text-xs text-white outline-none focus:border-primary/50 transition-colors"
                        >
                          {initialProjects.map((proj) => (
                            <option key={proj.id} value={proj.id} className="bg-zinc-950 text-white">
                              {proj.name}
                            </option>
                          ))}
                        </select>
                      </div>

                      <button
                        onClick={handleGenerateAiReport}
                        disabled={isGeneratingAiReport || !selectedProjectId}
                        className="self-end inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-gradient-to-r from-primary to-accent hover:opacity-95 text-white text-xs font-bold shadow-lg shadow-primary/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
                      >
                        {isGeneratingAiReport ? (
                          <>
                            <RefreshCw className="w-4 h-4 animate-spin" />
                            Generando Reporte...
                          </>
                        ) : (
                          <>
                            <Sparkles className="w-4 h-4 text-white group-hover:scale-110 transition-transform" />
                            Generar con IA
                          </>
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Loading Progress State */}
                  {isGeneratingAiReport && (
                    <div className="p-8 flex flex-col items-center justify-center text-center gap-4 border border-dashed border-primary/20 rounded-xl bg-primary/[0.01] animate-pulse">
                      <div className="relative">
                        <div className="w-16 h-16 rounded-full border-4 border-primary/20 border-t-primary animate-spin" />
                        <Sparkles className="w-6 h-6 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
                      </div>
                      <div className="space-y-1">
                        <h4 className="font-bold text-sm text-white">{aiReportProgress}% completado</h4>
                        <p className="text-xs text-muted-foreground animate-bounce">{aiReportStatus}</p>
                      </div>
                      
                      {/* Elegant animated progress bar */}
                      <div className="w-full max-w-md bg-white/5 h-2 rounded-full overflow-hidden border border-white/10 mt-2">
                        <div 
                          className="bg-gradient-to-r from-primary to-accent h-full transition-all duration-500 ease-out"
                          style={{ width: `${aiReportProgress}%` }}
                        />
                      </div>
                    </div>
                  )}

                  {/* Generated Report Content Container */}
                  {!isGeneratingAiReport && aiReportText && (
                    <div className="border border-border/50 rounded-xl overflow-hidden bg-black/40">
                      {/* Toolbar header */}
                      <div className="px-5 py-3 border-b border-border/50 bg-white/[0.01] flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                        <div className="flex items-center gap-3">
                          {/* Segment Control / Toggle */}
                          <div className="bg-white/5 border border-white/10 p-0.5 rounded-lg flex">
                            <button
                              onClick={() => setViewMode('visual')}
                              className={`px-3 py-1 text-[11px] font-bold rounded-md transition-all ${
                                viewMode === 'visual'
                                  ? 'bg-gradient-to-r from-primary to-accent text-white shadow'
                                  : 'text-muted-foreground hover:text-white'
                              }`}
                            >
                              ✨ Vista Visual Premium
                            </button>
                            <button
                              onClick={() => setViewMode('markdown')}
                              className={`px-3 py-1 text-[11px] font-bold rounded-md transition-all ${
                                viewMode === 'markdown'
                                  ? 'bg-gradient-to-r from-primary to-accent text-white shadow'
                                  : 'text-muted-foreground hover:text-white'
                              }`}
                            >
                              📝 Código Markdown
                            </button>
                          </div>
                        </div>
                        
                        <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap">
                          <button
                            onClick={handleCopyReport}
                            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 text-white text-[11px] font-semibold transition-all"
                          >
                            {copiedReport ? (
                              <>
                                <Check className="w-3.5 h-3.5 text-green-400" />
                                <span className="text-green-400">¡Copiado!</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-3.5 h-3.5 text-muted-foreground" />
                                <span>Copiar Reporte</span>
                              </>
                            )}
                          </button>

                          <button
                            onClick={handleDownloadReport}
                            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 text-white text-[11px] font-semibold transition-all"
                          >
                            <Download className="w-3.5 h-3.5 text-muted-foreground" />
                            <span>Descargar (.md)</span>
                          </button>

                          <button
                            onClick={handleDownloadHtmlReport}
                            className="inline-flex items-center gap-1 px-3.5 py-1.5 rounded-lg bg-primary/10 border border-primary/20 hover:bg-primary/20 text-primary text-[11px] font-bold shadow-lg shadow-primary/5 transition-all"
                          >
                            <Sparkles className="w-3.5 h-3.5 text-primary animate-pulse" />
                            <span>Descargar (.html Visual)</span>
                          </button>
                        </div>
                      </div>

                      {/* Display mode selection conditional */}
                      {viewMode === 'markdown' ? (
                        <div className="p-6 overflow-y-auto max-h-[500px] text-xs leading-relaxed text-slate-300 font-mono space-y-4 whitespace-pre-wrap select-text selection:bg-primary/30">
                          {aiReportText}
                        </div>
                      ) : (
                        (() => {
                          const data = parseMarkdownReport(aiReportText);
                          return (
                            <div className="p-6 overflow-y-auto max-h-[700px] space-y-6 text-sm text-slate-300 bg-zinc-950/60 font-sans select-text">
                              {/* Fallback Warning Alert */}
                              {isAiFallback && (
                                <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-4 flex items-start gap-3 animate-pulse">
                                  <AlertCircle className="w-5 h-5 text-yellow-400 shrink-0 mt-0.5" />
                                  <div className="space-y-1">
                                    <h5 className="text-xs font-bold text-yellow-400">Modo de Resiliencia Activo</h5>
                                    <p className="text-[10px] text-yellow-200/70 leading-relaxed">
                                      La API de IA no respondió a tiempo. El sistema ha generado este informe utilizando algoritmos deterministas locales para garantizar la continuidad del servicio.
                                    </p>
                                  </div>
                                </div>
                              )}

                              {/* White-label signature banner */}
                              <div className="bg-gradient-to-r from-primary/10 to-accent/10 border border-primary/20 rounded-xl p-5 relative overflow-hidden">
                                <div className="absolute top-0 right-0 w-48 h-48 bg-primary/5 rounded-full blur-3xl pointer-events-none" />
                                <span className="text-[10px] font-extrabold uppercase tracking-wider text-primary">
                                  Desde Strategic Connex (strategicconnex.com.ar)
                                </span>
                                <h3 className="text-lg font-bold text-white mt-1.5 font-display">
                                  Reporte de Auditoría SEO Ejecutiva
                                </h3>
                                <p className="text-xs text-muted-foreground mt-1">
                                  Proyecto analizado: <strong className="text-slate-200">{data.title}</strong> &bull; Generado hoy con Inteligencia Artificial
                                </p>
                              </div>

                              {/* Executive Summary Card */}
                              <div className="glass-card border border-white/10 rounded-xl p-5 space-y-3">
                                <h4 className="font-bold text-white flex items-center gap-2 border-b border-white/5 pb-2">
                                  <FileText className="w-4 h-4 text-primary" />
                                  🏢 Resumen Ejecutivo
                                </h4>
                                <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-line">
                                  {data.summary}
                                </p>
                              </div>

                              {/* Performance Analysis Card */}
                              <div className="glass-card border border-white/10 rounded-xl p-5 space-y-4">
                                <h4 className="font-bold text-white flex items-center gap-2 border-b border-white/5 pb-2">
                                  <BarChart3 className="w-4 h-4 text-primary" />
                                  📈 Análisis de Rendimiento y Visibilidad
                                </h4>
                                <p className="text-xs text-slate-300 leading-relaxed">
                                  {data.performanceIntro}
                                </p>
                                
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-2">
                                  {data.tableRows.map((row, idx) => (
                                    <div key={idx} className="bg-white/[0.02] border border-white/5 p-3 rounded-lg flex justify-between items-center">
                                      <div>
                                        <span className="text-[10px] font-medium text-muted-foreground uppercase tracking-wider block">
                                          {row.metric}
                                        </span>
                                        <span className="text-sm font-bold text-white mt-0.5 block">
                                          {row.value}
                                        </span>
                                      </div>
                                      <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-white/5 text-slate-300 border border-white/10">
                                        {row.status}
                                      </span>
                                    </div>
                                  ))}
                                </div>
                              </div>

                              {/* Technical Health & Speed Card */}
                              <div className="glass-card border border-white/10 rounded-xl p-5 space-y-4">
                                <h4 className="font-bold text-white flex items-center gap-2 border-b border-white/5 pb-2">
                                  <Activity className="w-4 h-4 text-primary" />
                                  🛠️ Diagnóstico de Salud Técnica y Velocidad
                                </h4>
                                
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                                  {/* Score Circle */}
                                  <div className="flex flex-col items-center justify-center text-center p-3 border border-white/5 bg-white/[0.01] rounded-lg">
                                    <div className="w-20 h-20 rounded-full border-2 border-primary/50 flex items-center justify-center font-bold text-2xl text-primary bg-primary/5 shadow-lg shadow-primary/10">
                                      {data.healthScore}
                                    </div>
                                    <span className="text-[10px] font-bold text-primary mt-2 uppercase tracking-wide">
                                      {data.healthClassification}
                                    </span>
                                  </div>

                                  {/* Speed Metrics Bars */}
                                  <div className="md:col-span-2 space-y-3">
                                    {/* LCP */}
                                    <div className="space-y-1">
                                      <div className="flex justify-between text-xs">
                                        <span className="text-muted-foreground">Largest Contentful Paint (LCP)</span>
                                        <strong className="text-white">{data.lcp}</strong>
                                      </div>
                                      <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                                        <div className="h-full bg-gradient-to-r from-primary to-accent rounded-full" style={{ width: '85%' }} />
                                      </div>
                                    </div>

                                    {/* INP */}
                                    <div className="space-y-1">
                                      <div className="flex justify-between text-xs">
                                        <span className="text-muted-foreground">Interaction to Next Paint (INP)</span>
                                        <strong className="text-white">{data.inp}</strong>
                                      </div>
                                      <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                                        <div className="h-full bg-gradient-to-r from-primary to-accent rounded-full" style={{ width: '68%' }} />
                                      </div>
                                    </div>

                                    {/* CLS */}
                                    <div className="space-y-1">
                                      <div className="flex justify-between text-xs">
                                        <span className="text-muted-foreground">Cumulative Layout Shift (CLS)</span>
                                        <strong className="text-white">{data.cls}</strong>
                                      </div>
                                      <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                                        <div className="h-full bg-gradient-to-r from-primary to-accent rounded-full" style={{ width: '92%' }} />
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>

                              {/* Prioritized Action Plan Card */}
                              <div className="glass-card border border-white/10 rounded-xl p-5 space-y-4">
                                <h4 className="font-bold text-white flex items-center gap-2 border-b border-white/5 pb-2">
                                  <CheckCircle2 className="w-4 h-4 text-primary" />
                                  🎯 Plan de Acción Priorizado para el Próximo Mes
                                </h4>
                                
                                <div className="space-y-3">
                                  {data.planItems.map((item, index) => (
                                    <div key={index} className="flex gap-3 bg-white/[0.01] border border-white/5 rounded-lg p-3 hover:bg-white/[0.02] transition-colors">
                                      <div className="w-6 h-6 rounded-full bg-primary/10 border border-primary/20 text-primary flex items-center justify-center font-bold text-xs flex-shrink-0">
                                        {index + 1}
                                      </div>
                                      <div className="space-y-1 flex-1">
                                        <div className="flex justify-between items-baseline gap-2">
                                          <h5 className="font-bold text-xs text-white">{item.title}</h5>
                                          <span className={`text-[9px] font-extrabold uppercase px-1.5 py-0.5 rounded border ${
                                            item.priority === 'Alta' 
                                              ? 'bg-red-500/10 text-red-400 border-red-500/20' 
                                              : item.priority === 'Media'
                                              ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20'
                                              : 'bg-blue-500/10 text-blue-400 border-blue-500/20'
                                          }`}>
                                            {item.priority}
                                          </span>
                                        </div>
                                        <p className="text-xs text-slate-400 leading-relaxed">
                                          {item.desc}
                                        </p>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            </div>
                          );
                        })()
                      )}
                    </div>
                  )}

                  {/* No report state */}
                  {!isGeneratingAiReport && !aiReportText && (
                    <div className="p-8 flex flex-col items-center justify-center text-center gap-3 border border-dashed border-white/10 rounded-xl bg-white/[0.005]">
                      <Sparkles className="w-8 h-8 text-muted-foreground/40" />
                      <div>
                        <h4 className="font-bold text-sm text-white">¿Listo para el reporte ejecutivo con IA?</h4>
                        <p className="text-xs text-muted-foreground mt-1 max-w-sm">Haz clic en el botón superior para realizar la fusión de datos y que Gemini elabore la auditoría automatizada.</p>
                      </div>
                    </div>
                  )}
                </div>

                {/* Audit Logs table */}
                <div className="glass-card rounded-xl overflow-hidden border border-border/50">
                  <div className="p-6 border-b border-border/50 bg-white/[0.01]">
                    <h3 className="font-bold text-white text-sm">Historial de Reportes Sincronizados</h3>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="border-b border-border/30 bg-white/[0.005] text-[10px] font-bold uppercase text-muted-foreground tracking-wider">
                          <th className="px-6 py-4">Reporte</th>
                          <th className="px-6 py-4">Formato</th>
                          <th className="px-6 py-4">Destino</th>
                          <th className="px-6 py-4">Última Generación</th>
                          <th className="px-6 py-4 text-center">Estado</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border/20 text-sm text-muted-foreground">
                        <tr className="hover:bg-white/[0.005] transition-colors">
                          <td className="px-6 py-4 font-semibold text-white">Full Technical Audit</td>
                          <td className="px-6 py-4"><span className="text-xs bg-white/5 border border-white/10 px-1.5 py-0.5 rounded font-mono font-medium">PDF</span></td>
                          <td className="px-6 py-4 text-xs font-mono">https://strategicaudit.pro/api/...</td>
                          <td className="px-6 py-4 text-xs">Hace 2 horas</td>
                          <td className="px-6 py-4 text-center">
                            <span className="inline-flex items-center gap-1 text-xs bg-green-500/10 border border-green-500/20 text-green-400 px-2.5 py-0.5 rounded-full font-medium">
                              <CheckCircle2 className="w-3.5 h-3.5" /> Completado
                            </span>
                          </td>
                        </tr>
                        <tr className="hover:bg-white/[0.005] transition-colors">
                          <td className="px-6 py-4 font-semibold text-white">Performance Metrics Feed</td>
                          <td className="px-6 py-4"><span className="text-xs bg-white/5 border border-white/10 px-1.5 py-0.5 rounded font-mono font-medium">JSON</span></td>
                          <td className="px-6 py-4 text-xs font-mono">https://strategicaudit.pro/feed/...</td>
                          <td className="px-6 py-4 text-xs">Hace 1 día</td>
                          <td className="px-6 py-4 text-center">
                            <span className="inline-flex items-center gap-1 text-xs bg-green-500/10 border border-green-500/20 text-green-400 px-2.5 py-0.5 rounded-full font-medium">
                              <CheckCircle2 className="w-3.5 h-3.5" /> Completado
                            </span>
                          </td>
                        </tr>
                        <tr className="hover:bg-white/[0.005] transition-colors">
                          <td className="px-6 py-4 font-semibold text-white">Keywords SERP Export</td>
                          <td className="px-6 py-4"><span className="text-xs bg-white/5 border border-white/10 px-1.5 py-0.5 rounded font-mono font-medium">CSV</span></td>
                          <td className="px-6 py-4 text-xs font-mono">https://strategicaudit.pro/export/...</td>
                          <td className="px-6 py-4 text-xs">Hace 3 días</td>
                          <td className="px-6 py-4 text-center">
                            <span className="inline-flex items-center gap-1 text-xs bg-green-500/10 border border-green-500/20 text-green-400 px-2.5 py-0.5 rounded-full font-medium">
                              <CheckCircle2 className="w-3.5 h-3.5" /> Completado
                            </span>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>
      </main>

      {/* Floating AI Copilot Widget */}
      <AiCopilot contextData={dashboardData} />
    </div>
  );
}

// Sub-components
function ProjectCard({ project }: { project: any }) {
  const getHealthColor = (score: number) => {
    if (score > 80) return 'text-green-400 bg-green-400/10 border-green-400/20';
    if (score > 50) return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20';
    return 'text-red-400 bg-red-400/10 border-red-400/20';
  };

  const healthScore = project.latestAudit ? 85 : 45;

  return (
    <Link href={`/projects/${project.id}`} className="block">
      <div className="glass-card rounded-xl p-6 group hover:border-primary/30 transition-colors cursor-pointer flex flex-col gap-6 relative overflow-hidden h-full">
        {/* Decorative background blob */}
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-primary/5 rounded-full blur-3xl group-hover:bg-primary/10 transition-colors pointer-events-none" />

        <div className="flex items-start justify-between relative z-10 min-w-0">
          <div className="min-w-0 flex-1 pr-3">
            <h3 className="text-lg font-bold tracking-tight text-white group-hover:text-primary transition-colors truncate" title={project.name}>
              {project.name}
            </h3>
            <p className="text-xs text-muted-foreground truncate" title={project.domain}>{project.domain}</p>
          </div>
          <div className={`w-12 h-12 rounded-full border flex items-center justify-center font-bold text-sm shrink-0 ${getHealthColor(healthScore)}`}>
            {healthScore}
          </div>
        </div>

        <div className="flex items-center gap-4 text-xs text-muted-foreground relative z-10">
          <div className="flex items-center gap-1.5 shrink-0">
            <Activity className="w-4 h-4 text-primary" />
            <span>{project.latestAudit?.status === 'completed' ? 'Auditado' : 'Pendiente'}</span>
          </div>
          <div className="w-1 h-1 rounded-full bg-border" />
          <div className="flex items-center gap-1.5 shrink-0">
            <Globe className="w-4 h-4 text-accent" />
            <span>{project.integrations?.length || 0} Integraciones</span>
          </div>
        </div>

        <div className="pt-4 border-t border-border/50 flex items-center justify-between relative z-10">
          <span className="text-[10px] text-muted-foreground">
            Actualizado {new Date(project.updatedAt).toLocaleDateString()}
          </span>
          <span className="text-xs text-primary hover:text-primary/80 font-semibold flex items-center gap-1 transition-colors">
            Ver Detalles <ChevronRight className="w-3.5 h-3.5" />
          </span>
        </div>
      </div>
    </Link>
  );
}
