/**
 * report-utils.ts
 * Pure utility functions for parsing and generating AI-generated SEO reports.
 * Extracted from DashboardContainer to enable isolated testing and reuse.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ParsedReport {
  title: string;
  summary: string;
  performanceIntro: string;
  tableRows: { metric: string; value: string; status: string }[];
  healthScore: number;
  healthClassification: string;
  lcp: string;
  inp: string;
  cls: string;
  planItems: { title: string; desc: string; priority: 'Alta' | 'Media' | 'Baja' }[];
}

// ─── Parser ───────────────────────────────────────────────────────────────────

/**
 * Parses a Markdown report generated by Gemini / fallback into a structured
 * data object suitable for rendering the high-impact visual HTML preview.
 */
export function parseMarkdownReport(text: string): ParsedReport {
  let title = "Reporte Estratégico Mensual SEO";
  let summary = "";
  let performanceIntro = "";
  let tableRows: ParsedReport['tableRows'] = [];
  let healthScore = 85;
  let healthClassification = "Excelente";
  let lcp = "1.8s";
  let inp = "210ms";
  let cls = "0.03";
  let planItems: ParsedReport['planItems'] = [];

  // Parse Title: "# 📊 Reporte Estratégico Mensual SEO — ..."
  const titleMatch = text.match(/# 📊 Reporte Estratégico Mensual SEO —\s*(.*)/i);
  if (titleMatch) title = titleMatch[1].trim();

  // Split by ## headers
  const sections = text.split(/##\s+/);
  for (const section of sections) {
    if (section.startsWith("🏢 Resumen Ejecutivo") || section.toLowerCase().includes("resumen ejecutivo")) {
      summary = section.replace(/^(🏢\s*)?Resumen Ejecutivo\s*/i, "").trim().split("---")[0].trim();

    } else if (section.startsWith("📈 Análisis de Rendimiento") || section.toLowerCase().includes("rendimiento y visibilidad")) {
      const perfSection = section.replace(/^(📈\s*)?Análisis de Rendimiento y Visibilidad\s*/i, "").trim().split("---")[0].trim();

      const tableLines = perfSection.match(/\|([^|\n]+)\|([^|\n]+)\|([^|\n]+)\|/g);
      if (tableLines) {
        tableRows = tableLines
          .map(line => line.split("|").map(c => c.trim()).filter(Boolean))
          .filter(cells => {
            if (cells.length < 3) return false;
            if (cells[0].includes("---") || cells[0].toLowerCase().includes("métrica")) return false;
            return true;
          })
          .map(cells => ({
            metric: cells[0].replace(/\*\*/g, ""),
            value: cells[1],
            status: cells[2]
          }));
      }

      performanceIntro = perfSection.split(/\|/)[0].trim();

    } else if (section.startsWith("🛠️ Diagnóstico de Salud") || section.toLowerCase().includes("salud técnica y velocidad")) {
      const healthPart = section.replace(/^(🛠️\s*)?Diagnóstico de Salud Técnica y Velocidad\s*/i, "").trim().split("---")[0].trim();

      const scoreMatch = healthPart.match(/(?:#+\s*)?🏆\s*(\d+)\s*\/\s*100/i);
      if (scoreMatch) healthScore = parseInt(scoreMatch[1], 10);

      const classificationMatch = healthPart.match(/Clasificación:\s*([^*|\n]+)/i);
      if (classificationMatch) healthClassification = classificationMatch[1].trim();

      const lcpMatch = healthPart.match(/Largest Contentful Paint \(LCP\):\s*([^*|\n]+)/i);
      if (lcpMatch) lcp = lcpMatch[1].trim();

      const inpMatch = healthPart.match(/Interaction to Next Paint \(INP\):\s*([^*|\n]+)/i);
      if (inpMatch) inp = inpMatch[1].trim();

      const clsMatch = healthPart.match(/Cumulative Layout Shift \(CLS\):\s*([^*|\n]+)/i);
      if (clsMatch) cls = clsMatch[1].trim();

    } else if (section.startsWith("🎯 Plan de Acción") || section.toLowerCase().includes("plan de acción")) {
      const planPart = section.replace(/^(🎯\s*)?Plan de Acción Priorizado[^]*?\n/i, "").trim().split("---")[0].trim();

      const lines = planPart.split("\n");
      let currentItem: ParsedReport['planItems'][number] | null = null;

      for (const line of lines) {
        const matchNum = line.match(/^\d+\.\s+\*\*([^*]+)\*\*:(.*)/);
        if (matchNum) {
          if (currentItem) planItems.push(currentItem);

          let priority: 'Alta' | 'Media' | 'Baja' = 'Media';
          if (matchNum[1].toLowerCase().includes("alta")) priority = 'Alta';
          else if (matchNum[1].toLowerCase().includes("baja")) priority = 'Baja';

          currentItem = {
            title: matchNum[1].replace(/\((?:Prioridad\s*)?(?:Alta|Media|Baja)\)/i, "").trim(),
            desc: matchNum[2].trim(),
            priority,
          };
        } else if (line.trim().startsWith("*") || line.trim().startsWith("-")) {
          if (currentItem) currentItem.desc += "\n" + line.trim();
        } else if (line.trim() && currentItem) {
          currentItem.desc += "\n" + line.trim();
        }
      }
      if (currentItem) planItems.push(currentItem);
    }
  }

  // Fallback plan items when AI provides none
  if (planItems.length === 0) {
    planItems = [
      { title: "Optimización de Metaetiquetas SEO", desc: "Ajustar descripciones emocionales para aumentar CTR.", priority: "Alta" },
      { title: "Mejora de Core Web Vitals", desc: "Reducir tiempo de interacción retrasando scripts no críticos.", priority: "Media" },
      { title: "Marcado de Datos Estructurados JSON-LD", desc: "Implementar Schema para capturar fragmentos enriquecidos en Google.", priority: "Media" },
    ];
  }

  return {
    title,
    summary: summary || "Informe preparado para analizar el posicionamiento orgánico, salud técnica y conversiones del dominio.",
    performanceIntro: performanceIntro || "El tráfico orgánico ha mantenido una excelente interacción.",
    tableRows: tableRows.length > 0 ? tableRows : [
      { metric: "Clicks Orgánicos", value: "8,420", status: "🟢 Estable (+4.6% vs periodo anterior)" },
      { metric: "Impresiones Totales", value: "124.8K", status: "🟢 Incremento en visibilidad" },
      { metric: "CTR Promedio", value: "6.74%", status: "🟡 Estable" },
      { metric: "Posición Promedio", value: "#4.2", status: "🟢 Top 5 principal" },
    ],
    healthScore,
    healthClassification,
    lcp,
    inp,
    cls,
    planItems,
  };
}

// ─── Sanitizer ────────────────────────────────────────────────────────────────

/** Escapes HTML special characters to prevent XSS in generated reports. */
export function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// ─── HTML Generator ───────────────────────────────────────────────────────────

/**
 * Generates a fully self-contained, print-ready HTML report document
 * using the Cybersecurity + Oil & Gas design palette.
 */
export function generateHtmlReportDocument(data: ParsedReport): string {
  const sanitizedTitle = escapeHtml(data.title);
  const sanitizedSummary = escapeHtml(data.summary).replace(/\n/g, '<br>');
  const sanitizedIntro = escapeHtml(data.performanceIntro);

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reporte Estratégico SEO - ${sanitizedTitle}</title>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #F8FAFC;
      --card-bg: #FFFFFF;
      --border: #E2E8F0;
      --primary: #0C1929;
      --accent: #64748B;
      --text: #0C1929;
      --text-muted: #64748B;
      --ok: #10B981;
      --warn: #F59E0B;
      --crit: #EF4444;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: var(--bg);
      color: var(--text);
      font-family: 'Plus Jakarta Sans', sans-serif;
      padding: 3rem 2rem;
      line-height: 1.6;
    }
    .container { max-width: 1000px; margin: 0 auto; }
    .header-banner {
      background: linear-gradient(135deg, #e0f2fe 0%, #f0fdf4 100%);
      border: 1px solid var(--border);
      border-radius: 1.5rem;
      padding: 3rem;
      margin-bottom: 2.5rem;
      position: relative;
      overflow: hidden;
      box-shadow: 0 4px 24px rgba(12,25,41,0.08);
    }
    .signature-top {
      font-size: 0.85rem;
      font-weight: 700;
      color: var(--accent);
      text-transform: uppercase;
      letter-spacing: 0.15em;
      margin-bottom: 1rem;
    }
    h1 {
      font-family: 'Outfit', sans-serif;
      font-size: 2.5rem;
      font-weight: 800;
      line-height: 1.2;
      color: var(--primary);
      margin-bottom: 1rem;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1.5rem;
      margin-top: 2rem;
      border-top: 1px solid var(--border);
      padding-top: 1.5rem;
      color: var(--text-muted);
      font-size: 0.85rem;
    }
    .meta-item strong { color: var(--text); }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 1.25rem;
      padding: 2.5rem;
      margin-bottom: 2.5rem;
      box-shadow: 0 2px 12px rgba(12,25,41,0.05);
    }
    h2 {
      font-family: 'Outfit', sans-serif;
      font-size: 1.4rem;
      font-weight: 700;
      margin-bottom: 1.5rem;
      display: flex;
      align-items: center;
      gap: 0.75rem;
      color: var(--primary);
      border-bottom: 2px solid var(--border);
      padding-bottom: 0.75rem;
    }
    p { margin-bottom: 1rem; color: var(--accent); font-size: 0.95rem; }
    .table-container {
      width: 100%;
      overflow-x: auto;
      margin: 1.5rem 0;
      border-radius: 0.75rem;
      border: 1px solid var(--border);
    }
    table { width: 100%; border-collapse: collapse; text-align: left; font-size: 0.9rem; }
    th {
      background-color: #F1F5F9;
      padding: 1rem 1.25rem;
      font-weight: 600;
      color: var(--accent);
      border-bottom: 1px solid var(--border);
    }
    td { padding: 1rem 1.25rem; border-bottom: 1px solid var(--border); color: var(--text); }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #F8FAFC; }
    .health-grid { display: grid; grid-template-columns: 1fr; }
    @media (min-width: 768px) { .health-grid { grid-template-columns: 220px 1fr; gap: 2.5rem; } }
    .score-circle-container { display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; }
    .score-circle {
      width: 140px;
      height: 140px;
      border-radius: 50%;
      background: linear-gradient(135deg, #e0f2fe, #f0fdf4);
      border: 4px solid var(--ok);
      box-shadow: 0 0 20px rgba(16,185,129,0.15);
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: 'Outfit', sans-serif;
      font-size: 2.5rem;
      font-weight: 800;
      color: var(--primary);
      margin-bottom: 0.75rem;
    }
    .score-classification {
      font-size: 0.8rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--ok);
    }
    .metrics-list { display: flex; flex-direction: column; gap: 1.25rem; }
    .metric-bar-group {
      background: #F8FAFC;
      border: 1px solid var(--border);
      padding: 1.25rem;
      border-radius: 0.75rem;
    }
    .metric-label-row { display: flex; justify-content: space-between; margin-bottom: 0.5rem; font-size: 0.9rem; color: var(--accent); }
    .metric-value { font-weight: 700; color: var(--primary); }
    .progress-bar-bg { background: var(--border); height: 6px; border-radius: 9999px; overflow: hidden; }
    .progress-bar-fill { height: 100%; background: linear-gradient(to right, var(--ok), #34d399); border-radius: 9999px; }
    .action-list { display: flex; flex-direction: column; gap: 1.5rem; }
    .action-item-card {
      background: #F8FAFC;
      border: 1px solid var(--border);
      border-radius: 0.85rem;
      padding: 1.5rem;
      display: flex;
      gap: 1.25rem;
    }
    .action-num {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      background: #E0F2FE;
      border: 1px solid #BAE6FD;
      color: var(--primary);
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 0.9rem;
      flex-shrink: 0;
    }
    .action-content { flex: 1; }
    .action-title-row { display: flex; justify-content: space-between; align-items: baseline; gap: 1rem; margin-bottom: 0.5rem; }
    .action-title { font-weight: 700; color: var(--primary); font-size: 1rem; }
    .priority-tag { font-size: 0.7rem; font-weight: 700; text-transform: uppercase; padding: 0.15rem 0.5rem; border-radius: 4px; }
    .priority-Alta { background: rgba(239,68,68,0.1); color: #b91c1c; border: 1px solid rgba(239,68,68,0.2); }
    .priority-Media { background: rgba(245,158,11,0.1); color: #b45309; border: 1px solid rgba(245,158,11,0.2); }
    .priority-Baja { background: rgba(59,130,246,0.1); color: #1d4ed8; border: 1px solid rgba(59,130,246,0.2); }
    .action-desc { font-size: 0.9rem; color: var(--accent); line-height: 1.5; }
    footer {
      text-align: center;
      padding: 3rem 0;
      color: var(--text-muted);
      font-size: 0.8rem;
      border-top: 1px solid var(--border);
      margin-top: 3rem;
    }
    footer a { color: var(--primary); text-decoration: none; font-weight: 600; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header-banner">
      <div class="signature-top">Desde Strategic Connex (strategicconnex.com.ar)</div>
      <h1>Reporte Estratégico de Auditoría SEO</h1>
      <p style="color: var(--accent); margin-top: 0.5rem; font-size: 1.1rem;">Informe Ejecutivo Automatizado por Inteligencia Artificial</p>
      <div class="meta-grid">
        <div class="meta-item">Proyecto: <strong>${data.title}</strong></div>
        <div class="meta-item">Fecha de Generación: <strong>${new Date().toLocaleDateString('es-ES')}</strong></div>
        <div class="meta-item">Auditoría Técnica: <strong>Salud ${data.healthScore}/100</strong></div>
      </div>
    </div>

    <div class="card">
      <h2>🏢 Resumen Ejecutivo</h2>
      <p>${sanitizedSummary}</p>
    </div>

    <div class="card">
      <h2>📈 Análisis de Rendimiento y Visibilidad</h2>
      <p>${sanitizedIntro}</p>
      ${data.tableRows.length > 0 ? `
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Métrica SEO / Analítica</th>
              <th>Valor Registrado</th>
              <th>Estado / Tendencia</th>
            </tr>
          </thead>
          <tbody>
            ${data.tableRows.map(row =>
              `<tr><td><strong>${escapeHtml(row.metric)}</strong></td><td>${escapeHtml(row.value)}</td><td>${escapeHtml(row.status)}</td></tr>`
            ).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}
    </div>

    <div class="card">
      <h2>🛠️ Diagnóstico de Salud Técnica y Velocidad</h2>
      <div class="health-grid">
        <div class="score-circle-container">
          <div class="score-circle">${data.healthScore}</div>
          <div class="score-classification">${escapeHtml(data.healthClassification)}</div>
        </div>
        <div class="metrics-list">
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Largest Contentful Paint (LCP)</span>
              <span class="metric-value">${escapeHtml(data.lcp)}</span>
            </div>
            <div class="progress-bar-bg"><div class="progress-bar-fill" style="width: 85%;"></div></div>
          </div>
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Interaction to Next Paint (INP)</span>
              <span class="metric-value">${escapeHtml(data.inp)}</span>
            </div>
            <div class="progress-bar-bg"><div class="progress-bar-fill" style="width: 65%;"></div></div>
          </div>
          <div class="metric-bar-group">
            <div class="metric-label-row">
              <span>Cumulative Layout Shift (CLS)</span>
              <span class="metric-value">${escapeHtml(data.cls)}</span>
            </div>
            <div class="progress-bar-bg"><div class="progress-bar-fill" style="width: 92%;"></div></div>
          </div>
        </div>
      </div>
    </div>

    <div class="card">
      <h2>🎯 Plan de Acción Priorizado para el Próximo Mes</h2>
      <div class="action-list">
        ${data.planItems.map((item, index) =>
          `<div class="action-item-card">
            <div class="action-num">${index + 1}</div>
            <div class="action-content">
              <div class="action-title-row">
                <span class="action-title">${escapeHtml(item.title)}</span>
                <span class="priority-tag priority-${item.priority}">${item.priority}</span>
              </div>
              <div class="action-desc">${escapeHtml(item.desc).replace(/\n/g, '<br>')}</div>
            </div>
          </div>`
        ).join('')}
      </div>
    </div>

    <footer>
      <p>Reporte exclusivo de marca blanca diseñado para clientes de <strong>Strategic Connex</strong>.</p>
      <p style="margin-top: 0.5rem; font-size: 0.75rem;">© ${new Date().getFullYear()} <a href="https://strategicconnex.com.ar" target="_blank">strategicconnex.com.ar</a>. Todos los derechos reservados.</p>
    </footer>
  </div>
</body>
</html>`;
}
