source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "just-the-docs", "~> 0.10"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "github-pages", "~> 231", group: :jekyll_plugins
